import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import { AppProvider } from "./provider/useAppContext";
import { DrawingName, SystemLogo } from "@/public/assets/data/data";
import ViewerImage from "@/app/viewer-image";
//import toast from "react-hot-toast";
//toast.error("This didn't work.");

export const metadata: Metadata = {
  title: DrawingName,
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className="scrollbar-style" style={{ colorScheme: "dark" }} lang="fr">
      <body className="bg-black roboto-regular text-white select-none">
        <AppProvider>
          <ViewerImage />
          {/*<NavbarSystem />*/}
          <Toaster
            position="top-center"
            reverseOrder={false}
            toastOptions={{
              style: {
                background: "#000",
                color: "#fff",
                border: "1px solid #525252",
                zIndex: 500000,
              },
            }}
          />
          {children}
        </AppProvider>
      </body>
    </html>
  );
}
