import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import Navbar from "./(components)/navbar";
import { SparklesCore } from "@/components/ui/sparkles";
import { ViewerImage } from "./viewer-image";
import { AppProvider } from "./provider/useAppContext";
//import toast from "react-hot-toast";
//toast.error("This didn't work.");

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className="scrollbar-style" style={{ colorScheme: "dark" }} lang="fr">
      <body className="bg-black roboto-regular text-white select-none">
        <AppProvider>
          <ViewerImage />
          <Toaster
            position="top-center"
            reverseOrder={false}
            toastOptions={{
              style: {
                background: "#000",
                color: "#fff",
                border: "1px solid #525252",
              },
            }}
          />
          <Navbar />
          <div className="relative z-10">{children}</div>
          <SparklesCore
            id="tsparticlesfullpage"
            background="transparent"
            minSize={0.6}
            maxSize={1.4}
            particleDensity={3}
            speed={2}
            className="w-full fixed inset-0 h-screen z-0"
            particleColor="#ffffff"
          />
        </AppProvider>
      </body>
    </html>
  );
}
